# Generated by Django 3.2.16 on 2023-02-12 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20230212_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
