# Generated by Django 3.2.16 on 2023-02-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_user_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic_name',
            new_name='topic',
        ),
    ]
