# Generated by Django 3.2.16 on 2023-02-21 07:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_enrolled_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
