# Generated by Django 3.2.16 on 2023-03-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooklesson',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notebooklesson', to='elearning.lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='elearning.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_test', to='elearning.lesson'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videolesson', to='elearning.lesson'),
        ),
        migrations.DeleteModel(
            name='CourseDescription',
        ),
    ]
