# Generated by Django 3.2.16 on 2023-03-05 05:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_auto_20230305_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
