# Generated by Django 3.2.16 on 2023-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_auto_20230305_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
