# Generated by Django 3.2.16 on 2023-03-05 13:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_notebooklesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
