# Generated by Django 3.2.16 on 2023-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0018_auto_20230306_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(null=True, to='elearning.Question'),
        ),
    ]
