# Generated by Django 3.2.16 on 2023-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0019_auto_20230308_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'answer1', 'answer2', 'answer3', 'answer4', 'correct_answer')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('name', 'lesson')},
        ),
    ]
