# Generated by Django 3.2.16 on 2023-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_auto_20230308_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('questionid', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usertest',
            name='answers',
            field=models.ManyToManyField(null=True, to='elearning.Answer'),
        ),
    ]
